# Generated by Django 4.2 on 2023-04-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_alter_category_name_alter_currenttasks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_completed', to='affairs.category', verbose_name='Мои задачи'),
        ),
        migrations.AlterField(
            model_name='currenttasks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_tasks', to='affairs.category', verbose_name='Мои задачи'),
        ),
    ]
