# Generated by Django 4.2 on 2023-04-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_alter_completedtasks_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Текущие задачи')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_tasks', to='affairs.category', verbose_name='Мои задачи')),
            ],
            options={
                'verbose_name': 'Текущая задача',
                'verbose_name_plural': 'Текущие задачи',
            },
        ),
        migrations.RemoveField(
            model_name='currenttasks',
            name='category',
        ),
        migrations.DeleteModel(
            name='CompletedTasks',
        ),
        migrations.DeleteModel(
            name='CurrentTasks',
        ),
    ]
