# Generated by Django 4.2 on 2023-04-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0005_tasks_remove_currenttasks_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_tasks', to='affairs.category', verbose_name='Мои задачи'),
        ),
    ]
